### ISSUE TITLE
`stderr` and `stdout` capturing is flaky

### ISSUE THREAD

**Issue by shepmaster** [ci-reporter/ci_reporter#125]
Tests fail sporadically:

```
Failures:
  1) Output capture should return $stdout and $stderr to original value after finish
     Failure/Error: $stdout.object_id.should_not == out.object_id
       expected not: == 3654
                got:    3654
     # ./spec/ci/reporter/output_capture_spec.rb:38:in `(root)'
  2) Output capture should save stdout and stderr messages written during the test run
     Failure/Error: @suite.stdout.should == "Hello\n"
       expected: "Hello\n"
            got: nil (using ==)
     # ./spec/ci/reporter/output_capture_spec.rb:18:in `(root)'
  3) Output capture should capture only during run of owner test suite
     Failure/Error: @suite.stdout.should == "B"
       expected: "B"
            got: nil (using ==)
     # ./spec/ci/reporter/output_capture_spec.rb:54:in `(root)'
  4) Output capture should include system-out and system-err elements in the xml output
     Failure/Error: root.elements.to_a('//system-out').first.texts.first.to_s.strip.should == "Hello"
       expected: "Hello"
            got: "" (using ==)
     # ./spec/ci/reporter/output_capture_spec.rb:31:in `(root)'
```
